
#
#
# MAIN OUTPUT PATHS
#
#
OUT_DIR=build
MBR_BIN=$(OUT_DIR)/mbr.bin
BOOT_BIN=$(OUT_DIR)/bootloader.bin
KERNEL_BIN=$(OUT_DIR)/kikikernel.bin
DISK_IMG=$(OUT_DIR)/kikios.img


#
#
# TOOLS OUTPUT PATHS
#
#
DISKPART_EXE=$(OUT_DIR)/diskpart


BOOT_SRC=boot
KERNEL_SRC=kernel

CC=x86_64-elf-gcc
LD=x86_64-elf-ld

ASM=nasm
ASMFLAGS=

INCLUDES=-Iinclude

ENV_RESERVED_SECS=3
ENV_FILE_SYSTEM=FAT16
